// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/create": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/create";
  };
  "components/Layout.tsx": {
    id: "components/Layout";
    page: "/" | "/login" | "/create";
  };
  "routes/Main.tsx": {
    id: "routes/Main";
    page: "/";
  };
  "routes/Login.tsx": {
    id: "routes/Login";
    page: "/login";
  };
  "routes/CreateAccount.tsx": {
    id: "routes/CreateAccount";
    page: "/create";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "components/Layout": typeof import("./app/components/Layout.tsx");
  "routes/Main": typeof import("./app/routes/Main.tsx");
  "routes/Login": typeof import("./app/routes/Login.tsx");
  "routes/CreateAccount": typeof import("./app/routes/CreateAccount.tsx");
};